---
- hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - ufw
        #- mysql
